### PR TITLE
Updated dependency of react-native-animatable

### PR DESCRIPTION
**Pull request by mr-bat**
your code relies on react-native-animatable v. 0.6.1. In that version it uses React.PropTypes which soon is going to be deprecated.
So I updated the dependencies to avoid further problems.

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Hey @mr-bat , didn't expect someone was using this component, thanks for the update 👍 
You should remove react and react-native from the dependencies though!

**Comment by mmazzarolo** [comment]
P.S.: You should remove react and react-native from the dependencies though, since they should be simply used as peerDependencies (feel free to correct me if I'm wrong)

**Comment by mr-bat** [comment]
Your library was the exact thing I was looking for. I also made another checkbox version from your code, but I'm not sure I if my company lets me share them too.

**Comment by mr-bat** [comment]
Actually, npm was nagging about UNMET PEER DEPENDENCY, so I added them. I think they are necessary; otherwise, npm will keep nagging upon further installations.

**Comment by mmazzarolo** [comment]
They shouldn't be dependencies, take a look at [react-native-modal package.json](https://github.com/react-native-community/react-native-modal) for example.  
We can remove it from the peerDependencies too though.  
Also... this lib is importing the propTypes from `react` too, so the warning would not disappear just by merging this PR 😄

**Comment by mr-bat** [comment]
Yes, you were right. I was misunderstanding peer dependencies. I added 'prop-types' as well as fixing package.json.

**Comment by mmazzarolo** [comment]
One last thing... you're still importing the `PropTypes` from `React` 😅

**Comment by mr-bat** [comment]
"-import React, { Component, PropTypes } from 'react'
+import React, { Component } from 'react'
...
+import PropTypes from 'prop-types'"
--
No. Actually, I'm using them from the new 'prop-types' package.🤔
But feel free to correct me if I'm wrong.

**Comment by mmazzarolo** [comment]
My bad, I didn't notive the PR update. 
Merged!
Thanks @mr-bat :)

**Comment by mr-bat** [comment]
Your welcome!

**Pull request merged**
